### ISSUE TITLE
Demo of the Template and Map sheets.

### ISSUE THREAD

**Issue by noctusfields** [avirut/bursar#1]
I am having some difficulties setting up the google spread sheet for the script can run properly. I do not know if I am setting up the template/map sheets right for the script to run properly. Below is the error message i get back. I have the .env file filled out with the GID for each sheet (labeled Overview/Temp/Map) listed in the env file

The .env file also states that i should reference the readme file for more information but the readme file dose not contain any sheet setup instructions

`bursar  | Validating SimpleFIN credentials...
bursar  | SimpleFIN config validated.
bursar  | Validating Google Sheets config...
bursar  | Google Sheets API access validated.
bursar  | Google Sheets config validated.
bursar  | Performing initial data pull...
bursar  | Traceback (most recent call last):
bursar  |   File "/app/src/setup.py", line 89, in <module>
bursar  |     run_update(days_to_fetch=int(os.environ.get("SETUP_PULL_PAST_DAYS")))
bursar  |   File "/app/src/update.py", line 130, in run_update
bursar  |     maps = get_maps(maps_sheet)
bursar  |   File "/app/src/update.py", line 21, in get_maps
bursar  |     splits = [i for i, x in enumerate(maps_raw[1]) if x == ""] + [len(maps_raw[1])]
bursar  | IndexError: list index out of range`

**Comment by thiagogpa** [comment]
Hey not sure if you still need this, but I managed to make it work by adding the following on columns A,B of the Maps sheet:

| id        | id        |
|-----------|-----------|
| account   | account   |
| posted    | posted    |
| amount    | amount    |
| description | description |
| payee     | payee     |
| memo      | memo      |
| notes     | notes     |
| name      | name      |
